### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by takanamito** [mitaku/komachi_heartbeat#32]
Hi @mitaku.
Thank you for creating a good gem.

Yesterday I send a pull request #30.
It is merged and CI ran, then CI failed.
https://travis-ci.org/github/mitaku/komachi_heartbeat

I wil try to fix CI.
But do you want to support older versions of ruby CI?
In April 5th, Support of Ruby 2.4 is ended. [Support of Ruby 2.4 has ended](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/)

If you end support for older versions of Ruby, I'll send a CI fix pull request for Ruby 2.5 or higher.

**Comment by mitaku** [comment]
@takanamito 

Thank you for reporting.
And thank you for your contribution.

Drop support for older Ruby versions.

Can I get a Pull Request?

**Comment by takanamito** [comment]
OK. I send a CI fix Pull Request.

**Comment by takanamito** [comment]
Thank you reviewing!
